/**
 * Durable tunnel automation (KTD6) — replicates the hand-built hardened tunnel as code: a
 * dedicated forward-only keypair, an ssh_config alias (`User bgwtunnel`, key-pinned), a
 * LaunchAgent plist, and a keeper wrapper that preserves the 10-fast-fail SELF-DISABLE valve
 * (a dead/changed prod must stop the reconnect storm, not retry for months).
 *
 * Generators are pure (spec in, file contents out) so every artifact is testable without
 * touching launchd. With the default alias the derived paths/label match the live hand-built
 * setup exactly, so `ensure()` ADOPTS an existing tunnel instead of double-binding the port.
 * None of these artifacts live in the repo — all Mac-local; the host name comes from config.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync, appendFileSync } from "node:fs";
import { homedir } from "node:os";
import { join, dirname } from "node:path";
import { escapeRegExp } from "../security/secrets.js";
import type { Exec } from "./exec.js";
import { execCapture } from "./exec.js";

/**
 * Default LaunchAgent label scheme — matches the live hand-built label (already public in this
 * repo's HANDOFF runbook) so ensureTunnel ADOPTS the existing agent instead of double-binding
 * the port under a fresh label. Override via config `labelPrefix` / OBSCURA_LABEL_PREFIX.
 */
const DEFAULT_LABEL_PREFIX = "com.dvillavicencio";
/** The loud line the keeper logs when it boots itself out — the classifier keys on it. */
export const SELF_DISABLE_MARKER = "SELF-DISABLING";
/** Tunnel establishment grace: alive longer than this = healthy drop, resets the fail counter. */
const KEEPER_GRACE_S = 30;
/** Consecutive fast-fails before the keeper self-disables (~3–4 min at ThrottleInterval 10). */
const KEEPER_MAX_FAILS = 10;

export interface TunnelSpecOptions {
  /** ssh_config alias; also the artifact basename. Default matches the live setup. */
  alias: string;
  /** Prod host as this Mac resolves it — a fleet value, always from local config (KTD8). */
  hostName: string;
  /** Local forwarded port. KTD5: must stay 8080 or the gateway's Host check 403s everything. */
  localPort?: number;
  /** Forward target as prod loopback sees it. */
  gatewayHost?: string;
  /** LaunchAgent label prefix (reverse-DNS style). Default matches the live setup. */
  labelPrefix?: string;
  /** Injectable home directory for tests. */
  home?: string;
}

export interface TunnelSpec {
  alias: string;
  hostName: string;
  localPort: number;
  gatewayHost: string;
  label: string;
  home: string;
  keyPath: string;
  keeperDir: string;
  keeperPath: string;
  plistPath: string;
  logPath: string;
  sshConfigPath: string;
}

export function tunnelSpec(opts: TunnelSpecOptions): TunnelSpec {
  const home = opts.home ?? homedir();
  const alias = opts.alias;
  const labelPrefix = opts.labelPrefix ?? DEFAULT_LABEL_PREFIX;
  const keeperDir = join(home, "Library", "Application Support", alias);
  return {
    alias,
    hostName: opts.hostName,
    localPort: opts.localPort ?? 8080,
    gatewayHost: opts.gatewayHost ?? "127.0.0.1:8080",
    label: `${labelPrefix}.${alias}`,
    home,
    keyPath: join(home, ".ssh", alias),
    keeperDir,
    keeperPath: join(keeperDir, "tunnel-keeper.sh"),
    plistPath: join(home, "Library", "LaunchAgents", `${labelPrefix}.${alias}.plist`),
    logPath: join(home, "Library", "Logs", `${alias}.log`),
    sshConfigPath: join(home, ".ssh", "config"),
  };
}

/** The keeper wrapper launchd runs: hold the tunnel, count fast-fails, self-disable when dead. */
export function keeperScript(spec: TunnelSpec): string {
  return `#!/bin/sh
# ${spec.alias} keeper — run by the LaunchAgent ${spec.label} (generated by obscura)
#
# Forwards Mac 127.0.0.1:${spec.localPort} -> prod gateway ${spec.gatewayHost} over a RESTRICTED,
# NON-ROOT ssh tunnel (alias \`${spec.alias}\`, user bgwtunnel, key-only, authorized_keys pinned
# to restrict,port-forwarding,permitopen="${spec.gatewayHost}" — the key can ONLY forward this
# one port; it grants no shell and no other port).
#
# launchd (KeepAlive) auto-reconnects on every exit. This wrapper adds a SAFETY VALVE so a
# permanently-dead config (VPS gone/replaced, alias/HostName changed, key revoked, sshd down)
# can't silently reconnect-storm for months:
#   - tunnel stays up >= GRACE sec  -> "healthy", reset the fail counter
#   - tunnel dies in  <  GRACE sec  -> "failed to establish", count it
#   - MAX_FAILS consecutive fast-fails -> log loudly + \`launchctl bootout\` (self-disable)
# Re-enable after fixing with the bootstrap command printed in the log.
set -u

ALIAS="${spec.alias}"
LABEL="${spec.label}"
PLIST="${spec.plistPath}"
GRACE=${KEEPER_GRACE_S}          # ConnectTimeout is 10s, so a real "can't connect" dies well under this
MAX_FAILS=${KEEPER_MAX_FAILS}      # consecutive fast-failures before self-disable
STATE="${spec.keeperDir}"
COUNT="$STATE/fastfail.count"
mkdir -p "$STATE"

ts() { date '+%Y-%m-%dT%H:%M:%S'; }

start=$(date +%s)
/usr/bin/ssh -N -T -L ${spec.localPort}:${spec.gatewayHost} "$ALIAS"
rc=$?
elapsed=$(( $(date +%s) - start ))

if [ "$elapsed" -ge "$GRACE" ]; then
  rm -f "$COUNT"
  echo "$(ts) tunnel up \${elapsed}s then exited (rc=$rc) — healthy drop; launchd will reconnect"
  exit 0
fi

n=0; [ -f "$COUNT" ] && n=$(cat "$COUNT" 2>/dev/null || echo 0)
n=$(( n + 1 )); echo "$n" > "$COUNT"
echo "$(ts) tunnel died in \${elapsed}s (rc=$rc) — fast-fail \${n}/\${MAX_FAILS}"

if [ "$n" -ge "$MAX_FAILS" ]; then
  echo "$(ts) *** \${MAX_FAILS} consecutive fast failures — ${SELF_DISABLE_MARKER} the tunnel LaunchAgent. ***"
  echo "    Likely cause: prod VPS gone/replaced, the '\${ALIAS}' ssh alias or its"
  echo "    HostName changed, the bgwtunnel user/key was removed, or prod sshd is down."
  echo "    After fixing, re-enable with:"
  echo "        launchctl bootstrap gui/$(id -u) \\"$PLIST\\""
  rm -f "$COUNT"
  /bin/launchctl bootout "gui/$(id -u)/\${LABEL}" 2>/dev/null
  exit 0
fi
exit 0
`;
}

/** The LaunchAgent: KeepAlive + RunAtLoad, throttled, running the keeper (never ssh directly). */
export function launchAgentPlist(spec: TunnelSpec): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${spec.label}</string>

  <!-- Runs the keeper wrapper, which holds the ssh -L ${spec.localPort}(local) -> ${spec.gatewayHost}
       tunnel over the RESTRICTED, NON-ROOT alias \`${spec.alias}\`. All connection opts
       (BatchMode/ExitOnForwardFailure/ServerAlive*/ConnectTimeout) live in the ssh_config alias.
       The wrapper adds the SELF-DISABLE safety valve — see the script header + the log. -->
  <key>ProgramArguments</key>
  <array>
    <string>/bin/sh</string>
    <string>${spec.keeperPath}</string>
  </array>

  <!-- Restart whenever the keeper exits (link dropped, prod sshd restart, redeploy gap, reboot).
       The wrapper's fast-fail counter is what eventually stops a permanently-broken tunnel. -->
  <key>KeepAlive</key>
  <true/>
  <key>RunAtLoad</key>
  <true/>
  <!-- At least 10s between restarts so a briefly-down prod can't be hammer-reconnected. -->
  <key>ThrottleInterval</key>
  <integer>10</integer>
  <key>ProcessType</key>
  <string>Background</string>

  <key>StandardOutPath</key>
  <string>${spec.logPath}</string>
  <key>StandardErrorPath</key>
  <string>${spec.logPath}</string>
</dict>
</plist>
`;
}

/** The ssh_config alias: forward-only bgwtunnel user, dedicated key, fast-failing keepalives. */
export function sshConfigBlock(spec: TunnelSpec): string {
  return `Host ${spec.alias}
    HostName ${spec.hostName}
    User bgwtunnel
    IdentityFile ${spec.keyPath}
    IdentitiesOnly yes
    BatchMode yes
    ExitOnForwardFailure yes
    ServerAliveInterval 15
    ServerAliveCountMax 3
    ConnectTimeout 10
`;
}

/** The authorized_keys line prod's bgwtunnel user must pin this Mac's key to. */
export function authorizedKeysLine(spec: TunnelSpec, publicKey: string): string {
  return `restrict,port-forwarding,permitopen="${spec.gatewayHost}" ${publicKey.trim()}`;
}

export type AgentState = "running" | "stopped" | "self-disabled" | "not-bootstrapped";
export type PortOwner = "ours" | "foreign" | "none";

/**
 * Classify `launchctl print gui/<uid>/<label>` output (null = the print failed, i.e. the agent
 * is not loaded). Self-disabled is distinguished from never-bootstrapped by the keeper's loud
 * marker in the recent log tail.
 */
export function classifyAgentState(printOutput: string | null, logTail: string): AgentState {
  if (printOutput !== null) {
    const state = printOutput.match(/\bstate = (\w+)/)?.[1];
    if (state === "running" || /\bpid = \d+/.test(printOutput)) return "running";
    return "stopped";
  }
  const recent = logTail.split("\n").slice(-20);
  if (recent.some((line) => line.includes(SELF_DISABLE_MARKER))) return "self-disabled";
  return "not-bootstrapped";
}

/**
 * Classify who owns the local forwarded port from `lsof -iTCP:<port> -sTCP:LISTEN` output
 * (null = nothing listening). Our tunnel listens via ssh; anything else bound there means
 * `connect` must stop, not silently register against an unknown service.
 */
export function classifyPortOwner(lsofOutput: string | null): PortOwner {
  if (lsofOutput === null) return "none";
  const dataLines = lsofOutput.split("\n").filter((l) => l.trim() && !l.startsWith("COMMAND"));
  if (dataLines.length === 0) return "none";
  return dataLines.every((l) => l.split(/\s+/)[0] === "ssh") ? "ours" : "foreign";
}

export interface TunnelState {
  agent: AgentState;
  port: PortOwner;
  /** The keeper's why-it-died lines when self-disabled. */
  selfDisableReason?: string;
}

function readLogTail(spec: TunnelSpec): string {
  try {
    return readFileSync(spec.logPath, "utf8");
  } catch {
    return "";
  }
}

/** Collect live state (launchctl + lsof + log) and classify it. */
export async function tunnelState(spec: TunnelSpec, exec: Exec = execCapture): Promise<TunnelState> {
  const uid = process.getuid?.() ?? 0;
  const [print, lsof] = await Promise.all([
    exec("launchctl", ["print", `gui/${uid}/${spec.label}`]).catch(() => null),
    exec("lsof", ["-nP", `-iTCP:${spec.localPort}`, "-sTCP:LISTEN"]).catch(() => null),
  ]);
  const logTail = readLogTail(spec);
  const agent = classifyAgentState(print && print.code === 0 ? print.stdout : null, logTail);
  const port = classifyPortOwner(lsof && lsof.code === 0 ? lsof.stdout : null);
  if (agent !== "self-disabled") return { agent, port };
  const lines = logTail.split("\n");
  let at = 0;
  for (let i = lines.length - 1; i >= 0; i--) {
    if (lines[i]?.includes(SELF_DISABLE_MARKER)) {
      at = i;
      break;
    }
  }
  return { agent, port, selfDisableReason: lines.slice(at, at + 4).join("\n") };
}

export interface EnsureResult {
  /** Paths created this run (empty = everything already existed). */
  created: string[];
  /** A fresh keypair was generated — its pub half is NOT on prod yet. */
  newKeypair: boolean;
  /** When newKeypair: the authorized_keys line to pin on prod's bgwtunnel user. */
  installLine?: string;
  /**
   * Adopted artifacts whose load-bearing values disagree with the current config (ssh-alias
   * HostName, keeper forward spec). Existing files are never rewritten, so a config change
   * does NOT propagate — these warnings are the only way the operator learns that.
   */
  drift?: string[];
  action: "none" | "bootstrapped" | "re-enabled";
}

/** Compare adopted artifacts against the current spec; returns human-readable drift lines. */
function detectDrift(spec: TunnelSpec, sshConfig: string | null): string[] {
  const drift: string[] = [];
  if (sshConfig !== null) {
    // HostName inside our alias block only: scan from the alias line to the next Host line.
    const aliasRe = new RegExp(`^Host[ \\t]+${escapeRegExp(spec.alias)}[ \\t]*$`, "m");
    const start = sshConfig.search(aliasRe);
    if (start !== -1) {
      const rest = sshConfig.slice(start).split("\n").slice(1);
      const end = rest.findIndex((l) => /^Host[ \t]/.test(l));
      const block = (end === -1 ? rest : rest.slice(0, end)).join("\n");
      const hostName = block.match(/^[ \t]*HostName[ \t]+(\S+)/m)?.[1];
      if (hostName !== undefined && hostName !== spec.hostName) {
        drift.push(`ssh alias "${spec.alias}" points at HostName ${hostName}, but config says ${spec.hostName} — the tunnel dials the OLD host until you update ${spec.sshConfigPath}`);
      }
    }
  }
  if (existsSync(spec.keeperPath)) {
    const keeper = readFileSync(spec.keeperPath, "utf8");
    const forward = keeper.match(/-L[ \t]+(\S+)/)?.[1];
    const expected = `${spec.localPort}:${spec.gatewayHost}`;
    if (forward !== undefined && forward !== expected) {
      drift.push(`keeper forwards ${forward}, but config says ${expected} — regenerate ${spec.keeperPath} to apply the change`);
    }
  }
  return drift;
}

/**
 * Create absent artifacts (keypair, ssh alias, keeper, plist) and make the agent run:
 * not-bootstrapped → bootstrap; self-disabled → re-enable (same bootstrap, distinct intent);
 * already running → no-op. Existing artifacts are never overwritten — the live hand-built
 * tunnel is adopted, not replaced.
 */
export async function ensureTunnel(spec: TunnelSpec, exec: Exec = execCapture): Promise<EnsureResult> {
  const created: string[] = [];
  let newKeypair = false;
  let installLine: string | undefined;

  if (!existsSync(spec.keyPath)) {
    mkdirSync(dirname(spec.keyPath), { recursive: true, mode: 0o700 });
    const keygen = await exec("ssh-keygen", ["-t", "ed25519", "-f", spec.keyPath, "-N", "", "-C", `obscura-${spec.alias}`]);
    if (keygen.code !== 0) throw new Error(`ssh-keygen failed (exit ${keygen.code}): ${keygen.stderr.trim()}`);
    created.push(spec.keyPath);
    newKeypair = true;
    installLine = authorizedKeysLine(spec, readFileSync(`${spec.keyPath}.pub`, "utf8"));
  }

  const aliasRe = new RegExp(`^Host[ \\t]+${escapeRegExp(spec.alias)}[ \\t]*$`, "m");
  const sshConfig = existsSync(spec.sshConfigPath) ? readFileSync(spec.sshConfigPath, "utf8") : null;
  if (sshConfig === null) {
    mkdirSync(dirname(spec.sshConfigPath), { recursive: true, mode: 0o700 });
    writeFileSync(spec.sshConfigPath, sshConfigBlock(spec), { mode: 0o600 });
    created.push(spec.sshConfigPath);
  } else if (!aliasRe.test(sshConfig)) {
    appendFileSync(spec.sshConfigPath, `${sshConfig.endsWith("\n") ? "" : "\n"}\n${sshConfigBlock(spec)}`);
    created.push(`${spec.sshConfigPath} (Host ${spec.alias} block)`);
  }

  if (!existsSync(spec.keeperPath)) {
    mkdirSync(spec.keeperDir, { recursive: true });
    writeFileSync(spec.keeperPath, keeperScript(spec), { mode: 0o755 });
    created.push(spec.keeperPath);
  }

  if (!existsSync(spec.plistPath)) {
    mkdirSync(dirname(spec.plistPath), { recursive: true });
    writeFileSync(spec.plistPath, launchAgentPlist(spec), { mode: 0o644 });
    created.push(spec.plistPath);
  }
  mkdirSync(dirname(spec.logPath), { recursive: true });

  // Adopted artifacts are never rewritten — but silently keeping stale values (old HostName,
  // old forward) sends the operator chasing ghost failures. Surface the disagreement.
  const drift = detectDrift(spec, existsSync(spec.sshConfigPath) ? readFileSync(spec.sshConfigPath, "utf8") : null);

  const state = await tunnelState(spec, exec);
  if (state.agent === "running" || state.agent === "stopped") {
    // stopped = loaded, between KeepAlive restarts — launchd owns it; nothing to do.
    return { created, newKeypair, ...(installLine ? { installLine } : {}), ...(drift.length ? { drift } : {}), action: "none" };
  }
  const uid = process.getuid?.() ?? 0;
  const bootstrap = await exec("launchctl", ["bootstrap", `gui/${uid}`, spec.plistPath]);
  if (bootstrap.code !== 0) {
    throw new Error(`launchctl bootstrap failed (exit ${bootstrap.code}): ${bootstrap.stderr.trim()}`);
  }
  return {
    created,
    newKeypair,
    ...(installLine ? { installLine } : {}),
    ...(drift.length ? { drift } : {}),
    action: state.agent === "self-disabled" ? "re-enabled" : "bootstrapped",
  };
}

/** Stop + unload the agent (the set-and-forget off switch). */
export async function bootoutTunnel(spec: TunnelSpec, exec: Exec = execCapture): Promise<void> {
  const uid = process.getuid?.() ?? 0;
  await exec("launchctl", ["bootout", `gui/${uid}/${spec.label}`]); // already-gone is fine
}
